import React from 'react';

const firstName = [
    'A.T. Still', //
    'Abilene',
    'Christian',
    'Academy of Art',
    'Adams',
    'Adelphi',
    'Adler',
    'Adrian',
    'Advent',
    'Agnes Scott',
    'Air Force',
    'Alabama',
    'Alaska',
    'Albany',
    'Alfred',
    'Alice',
    'Alma',
    'Alvernia',
    'American',
    'Amberton',
    'Amherst',
    'Arcadia',
    'Arizona',
    'Arkansas',
    'Arlington',
    'Art',
    'Asbury',
    'Auburn',
    'Athens',
    'Augusta',
    'Augsburg',
    'Babson',
    'Bacone',
    'Baker',
    'Baldwin',
    'Ball',
    'Bank',
    'Baptist',
    'Barclay',
    'Bard',
    'Barnard',
    'Barry',
    'Barton',
    'Bastyr',
    'Bates',
    'Bay Path',
    'Baylor',
    'Beacon',
    'Beloit',
    'Becker',
    'Belhaven',
    'Bellarmine',
    'Bellavue',
    'Biola',
    'Bismark',
    'Cabarrus',
    'Cabrini',
    'Cairn',
    'Caldwell',
    'California',
    'Cameron',
    'Campbell',
    'Campbellsville',
    'Canisius',
    'Capital',
    'Cardinal',
    'Carlton',
    'Carlow',
    'Carnegie',
    'Carroll',
    'Carson',
    'Carthage',
    'Case',
    'Castleton',
    'Catawba',
    'Cazenovia',
    'Cedar',
    'Cedarville',
    'Centenary',
    'Central',
];

const collegeFirstName = (firstName: Array<string>) => {
    return firstName[Math.floor(Math.random() * (firstName.length - 1))];
};

const FirstClause = () => {
    return <div>{collegeFirstName(firstName)}</div>;
};

export default FirstClause;
